# Generated by Django 3.1.5 on 2021-01-11 19:54

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('SELECT\n                  row_number() over () as id,\n                  q.id as question_id,\n                  count(*) as total_choices\n              FROM question q\n                JOIN choice c on c.question_id = q.id\n              GROUP BY q.id', 'question_stat', engine='django.db.backends.sqlite3'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'question_stat', engine='django.db.backends.sqlite3'),
            atomic=False,
        ),
    ]
