name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install .[dev]
      - name: Run linter
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: prepare env
        run: cp example_env_file .env
      - name: Set up test databases
        run: docker compose up -d
      - name: install dependencies
        run: pip install .[tests]
      - name: run tests
        run: tox
