name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: "prepare env"
        run: cp example_env_file .env
      - name: "Set up test databases"
        run: docker compose up -d
      - name: "install dependencies"
        run: pip install -r requirements.txt
      - name: "run tests"
        run: tox
